services:
  postgres:
    container_name: ${POSTGRES_NAME} 
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
    restart: unless-stopped
    networks:
      - lockbox-net

  backend:
    container_name: lockbox-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${SERVER_PORT}
      BODY_LIMIT_MB: ${BODY_LIMIT_MB}
      STORAGE_LIMIT: ${STORAGE_LIMIT}
      FIBER_LIMIT_REQ: ${FIBER_LIMIT_REQ}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_URL: ${DB_CONTAINER_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: {MINIO_BUCKET}
      LOG_LEVEL: ${LOG_LEVEL}
      BACK_LOG_FILE: ${BACK_LOG_FILE}
    volumes:
      - ./data/logs/backend:/app/logs/:z
    depends_on:
      - postgres
      - minio
    restart: unless-stopped
    command: ./backend
    networks:
      - lockbox-net

  frontend:
    container_name: lockbox-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      NEXT_PUBLIC_SERVER: ${NEXT_PUBLIC_SERVER}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lockbox-net

  minio:
    container_name: lockbox-minio
    image: minio/minio:latest
    ports:
      - '9091:9091'
    volumes:
      - ./data/minio:/data:z
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --address ":9090" --console-address ":9091"
    restart: always
    networks:
      - lockbox-net

volumes:
  pgdata:
    name: lockbox-pg-data
  miniodata:
    name: lockbox-minio-data

networks:
  lockbox-net:
    name: lockbox-net
    driver: bridge
